FROM registry.fedoraproject.org/fedora-toolbox:38

# install VScodium
COPY vscodium.repo /etc/yum.repos.d/
RUN rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg \
    && dnf install -y codium

# install extra packages
COPY extra-packages /
RUN dnf install -y $(<extra-packages) \
    && dnf clean all
